sudo: false
language: node_js
node_js:
  - 4
  - 5
  - 6
after_success:
  - cat ./coverage/coverage.json | ./node_modules/.bin/adana -F . > ./coverage/istanbul.json
  - bash <(curl -s https://codecov.io/bash) -f ./coverage/istanbul.json
